# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
          . ~/.bashrc
          fi

# User specific environment and startup programs

#PATH=$PATH:$HOME/.local/bin:$HOME/bin
#export PATH

HOSTNAME=`/usr/bin/hostname 2> /dev/null`
export PATH=$HOME/bin
