# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

#PATH=$PATH:$HOME/.local/bin:$HOME/bin
#export PATH

# set hostname
HOSTNAME=`/usr/bin/hostname 2> /dev/null`
# link vimrc
ln -sf $HOME/vimrcs/vimrc_$HOSTNAME $HOME/.vimrc
# set path
export PATH=$HOME/bin

# disable Ctrl+D
export IGNOREEOF=10000

vim
